"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import { formatINR, formatPct, formatDate } from "@/lib/format";
import { Card, Badge, StatTile, ErrorBanner, EmptyState } from "@/components/ui";
import EquityCurveChart from "@/components/EquityCurveChart";

export default function BacktestDetailPage() {
  const { id } = useParams();
  const [bt, setBt] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!id) return;
    api.get(`/api/backtests/${id}`).then(setBt).catch((e) => setError(e.message));
  }, [id]);

  if (!bt) return error ? <ErrorBanner message={error} /> : <EmptyState>Loading…</EmptyState>;

  const metrics = bt.results?.metrics;
  const equityCurve = bt.results?.equityCurve || [];

  return (
    <div className="space-y-6">
      <ErrorBanner message={error} />
      <div>
        <h1 className="text-xl font-semibold">{bt.symbol} <span className="font-normal text-[#898781]">· {bt.strategy_name}</span></h1>
        <p className="text-sm text-[#898781]">{bt.start_date} – {bt.end_date} · <Badge status={bt.status === "completed" ? "good" : "critical"}>{bt.status}</Badge></p>
      </div>

      {bt.status === "failed" && <ErrorBanner message={bt.error} />}

      {metrics && (
        <>
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
            <StatTile label="Total return" value={formatPct(metrics.totalReturnPct)} tone={metrics.totalReturnPct >= 0 ? "good" : "bad"} />
            <StatTile label="CAGR" value={formatPct(metrics.cagrPct)} />
            <StatTile label="Win rate" value={formatPct(metrics.winRatePct)} />
            <StatTile label="Max drawdown" value={formatPct(metrics.maxDrawdownPct)} tone="bad" />
            <StatTile label="Trades" value={metrics.tradeCount} />
            <StatTile label="Total P&L" value={formatINR(metrics.totalPnl)} tone={metrics.totalPnl >= 0 ? "good" : "bad"} />
            <StatTile label="Total costs" value={formatINR(metrics.totalCosts)} />
            <StatTile label="Risk/reward" value={metrics.riskReward ?? "—"} />
          </div>

          <Card title="Equity curve">
            <EquityCurveChart points={equityCurve} startCapital={metrics.startCapital} />
          </Card>
        </>
      )}

      <Card title={`Trades (${bt.trades.length})`}>
        {bt.trades.length === 0 ? (
          <EmptyState>No trades were generated by this backtest.</EmptyState>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm tabular-nums">
              <thead>
                <tr className="border-b border-black/10 text-left text-xs text-[#898781] dark:border-white/10">
                  <th className="py-2 pr-4">Entry</th><th className="py-2 pr-4">Entry px</th><th className="py-2 pr-4">Exit</th><th className="py-2 pr-4">Exit px</th><th className="py-2 pr-4">Qty</th><th className="py-2 pr-4">P&L</th><th className="py-2 pr-4">Costs</th><th className="py-2 pr-4">Reason</th>
                </tr>
              </thead>
              <tbody>
                {bt.trades.map((t) => (
                  <tr key={t.id} className="border-b border-black/5 last:border-0 dark:border-white/5">
                    <td className="py-1.5 pr-4">{formatDate(t.entry_date)}</td>
                    <td className="py-1.5 pr-4">₹{t.entry_price.toFixed(2)}</td>
                    <td className="py-1.5 pr-4">{formatDate(t.exit_date)}</td>
                    <td className="py-1.5 pr-4">{t.exit_price ? `₹${t.exit_price.toFixed(2)}` : "—"}</td>
                    <td className="py-1.5 pr-4">{t.quantity}</td>
                    <td className={`py-1.5 pr-4 ${t.pnl >= 0 ? "text-[#006300] dark:text-[#0ca30c]" : "text-[#d03b3b] dark:text-[#e66767]"}`}>{formatINR(t.pnl)}</td>
                    <td className="py-1.5 pr-4 text-[#898781]">{formatINR(t.costs)}</td>
                    <td className="py-1.5 pr-4 text-[#898781]">{t.exit_reason}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
